### ISSUE TITLE
A better name?

### ISSUE THREAD

**Issue by TMagnusN** [W9pi3cZ1/openfrp_sdk#1]
Would it be better to call it 'caller' after reviewing the code?

**Comment by W9pi3cZ1** [comment]
no, I don't think it's a better name. because a better name should let others know what it does.

**Comment by TMagnusN** [comment]
But your implementation function is to call other APIs, not toolkits

**Comment by W9pi3cZ1** [comment]
Ok, I renamed this repo name, but it will cause some problems.😅
